# Generated by Django 5.1.2 on 2024-10-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
