# Generated by Django 5.1.2 on 2024-10-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_color_resource_group_taskresources_task_resources'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('date', 'priority')},
        ),
        migrations.AlterUniqueTogether(
            name='taskresources',
            unique_together={('task', 'resource')},
        ),
    ]
