# Generated by Django 5.1.2 on 2024-10-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_task_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
