# Generated by Django 5.1.2 on 2024-10-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(verbose_name=[(1, 'Low'), (2, 'Medium'), (3, 'High')]),
        ),
    ]
