# Generated by Django 5.1.2 on 2024-10-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Hight'), (2, 'Medium'), (3, 'Low')]),
        ),
    ]
