# Generated by Django 5.1.2 on 2024-10-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_auth',
            field=models.DateTimeField(null=True),
        ),
    ]
